---

- name: Install redis
  yum: name=redis state=latest
  notify: restart redis

- name: Copy redis.conf
  template: src=redis.conf dest=/etc/redis/redis.conf
  notify: restart redis

- name: Install php redis
  yum: name=php-redis state=latest
  notify: restart php7.0-fpm
